[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "streamlit-option-menu>=0.4.0",
    "streamlit>=1.45.0",
    "matplotlib>=3.10.1",
    "seaborn>=0.13.2",
    "tensorflow>=2.14.0",
    "scipy>=1.15.2",
    "plotly>=6.0.1",
    "pandas>=2.2.3",
    "numpy>=2.2.5",
    "scikit-learn>=1.6.1",
    "sqlalchemy>=2.0.40",
    "psycopg2-binary>=2.9.10",
    "reportlab>=4.4.0",
]
